name: Update appfilter from Arcticons

on:
  push:
    branches:
      - 'track-remote-appfilter'
  schedule:
    - cron: '47 15 * * *'

concurrency:
  group: 'track-remote-appfilter'
  cancel-in-progress: true

jobs:
  track-remote-appfilter:
    runs-on: ubuntu-latest
    steps:
      - name: Track Remote Appfilter
        uses: rdehenne/track-remote-appfilter@v0.0.1-alpha2

