name: Update appfilter from Arcticons

on:
  push:
    branches:
      - 'track-remote-appfilter'
  schedule:
    - cron: '47 15 * * *'

concurrency:
  group: 'track-remote-appfilter'
  cancel-in-progress: true

jobs:
  track-remote-appfilter:
    runs-on: ubuntu-latest
    steps:
      - name: Track Remote Appfilter
        uses: rdehenne/track-remote-appfilter@v0.0.1-alpha8
        with:
          local-appfilter: 'newicons/appfilter.xml'
          remote-appfilter: 'https://raw.githubusercontent.com/Arcticons-Team/Arcticons/refs/heads/main/newicons/appfilter.xml'
          commit-message: 'Add appfilter items from Arcticons'
          title: 'Add appfilter items from Arcticons'
          body: |
            This PR adds new appfilter items from Arcticons that could be matched to existing drawables.

            See Arcticons' [appfilter.xml](https://github.com/Arcticons-Team/Arcticons/blob/main/newicons/appfilter.xml) for more details.

